# Generated by Django 4.0.2 on 2022-03-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('salary', models.IntegerField(max_length=100)),
                ('contactInfo', models.CharField(max_length=100)),
            ],
        ),
    ]
