# Generated by Django 4.0.2 on 2022-03-31 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
    ]
